options(prompt="R> ",scipen=16,digits=4,warning=FALSE, message=FALSE)
library(Sim.DiffProc)


###

f <- expression(kappa / x) 
g <- expression(mu*sqrt(x/sigma)) 
tex <- TEX.sde(object = c(drift = f, diffusion = g))


###

f <- expression(-mu1 * x) 
g <- expression(mu2 * sqrt(x)) 
tex <- TEX.sde(object = c(drift = f, diffusion = g))
mem.mod1d <- MEM.sde(drift = f, diffusion = g)
tex <- TEX.sde(object = mem.mod1d)

###

f  <- expression(1/mu *(theta -x ) , x) 
g  <- expression(sqrt(sigma) , 0) 
tex <- TEX.sde(object = c(drift = f, diffusion = g))
mem.mod2d <- MEM.sde(drift = f, diffusion = g)
tex <- TEX.sde(object = mem.mod2d)
###

f <- expression(mu1*cos(mu2+z),mu1*sin(mu2+z),0) 
g <- expression(sigma,sigma,alpha) 
tex <- TEX.sde(object = c(drift = f, diffusion = g))
mem.mod3d <- MEM.sde(drift = f, diffusion = g)
tex <- TEX.sde(object = mem.mod3d)


###

res <- data.frame(x=c("a","b","c"),y=c(10,15,14))
tex <- TEX.sde(object = res, booktabs = TRUE, align = "r")

###

mu1=0.25; mu2=3; sigma=0.05; alpha=0.03
mod3d <- snssde3d(drift=f,diffusion=g,x0=c(x=0,y=0,z=0),M=50,T=10)

stat.fun3d <- function(data, i){
   d <- data[i,]
   return(c(mean(d$x),mean(d$y),mean(d$z), 
            var(d$x),var(d$y),var(d$z)))
			}
mcm.mod3d = MCM.sde(mod3d,statistic=stat.fun3d,R=10,parallel="snow",ncpus=2,
                    names=c("m1","m2","m3","S1","S2","S3"))
					
TEX.sde(object = mcm.mod3d, booktabs = TRUE, align = "r", caption ="\\LaTeX~ 
         table for Monte Carlo results generated by \\code{TEX.sde()} method.")
		 
###

TEX.sde(object=1)		
 
		 